title: Maria Camila Toledo
 ![Profilephoto](/assets/media/360_F_278687684_vXZpgT77CwU14zTwtrJh4dNUpt00K9a6.jpg)
logo:    ![Profilephoto](/assets/Linkedin.jpg)
description: Marketing Analytics Portfolio
show_downloads: true
build:
  hugo_version: '0.136.5'
